---
- name: deploy
  hosts: server
  become: yes
  vars:
    remote_work_dir: "/home/han/park"
  roles:
    - app_deploy

- name: dns and lb
  hosts: control
  become: yes
  vars:
    domain_name: "parking-17.com"
    host_ip: "192.168.56.10"
  roles:
    - dns_bind
    - haproxy_lb
