- name: buat direktori proyek
  file:
    path: "{{ remote_work_dir }}"
    state: directory
    mode: "0755"
    owner: han
    group: han

- name: copy code
  copy:
    src: "/home/han/park/"
    dest: "{{ remote_work_dir }}/"
    owner: han
    group: han
    mode: "0755"

- name: Kirim konfigurasi
  template:
    src: "{{ item.src }}"
    dest: "{{ remote_work_dir }}/{{ item.dest }}"
    owner: han
    group: han
    mode: "0644"
  loop:
    - { src: "supervisord.conf.j2", dest: "supervisord.conf" }
    - { src: "nginx.conf.j2", dest: "nginx.conf" }
    - { src: "Dockerfile.j2", dest: "Dockerfile" }
    - { src: "docker-compose.yml.j2", dest: "docker-compose.yml" }

- name: sinkronisasi waktu sistem dengan timezone
  shell: |
    timedatectl set-timezone Asia/Jakarta
    systemctl restart systemd-timesyncd
    sleep 1
    timedatectl set-ntp true
  failed_when: false

- name: clear kontainer lama
  shell: |
    sg docker -c "docker compose down -v"
    sg docker -c "docker volume prune -f"
  args:
    chdir: "{{ remote_work_dir }}"
  become_user: han
  failed_when: false

- name: build image dan jalankan container
  shell: |
    sg docker -c "docker compose up -d --build"
  args:
    chdir: "{{ remote_work_dir }}"
  become_user: han
  failed_when: false
