- name: install haproxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: direktori penyimpanan sertifikat ssl
  file:
    path: /etc/haproxy/ssl
    state: directory

- name: buat certificate untuk haproxy
  shell: |
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/haproxy/ssl/parking.key \
    -out /etc/haproxy/ssl/parking.crt \
    -subj "/C=ID/ST=Jakarta/L=Jakarta/O=Sekolah/OU=IT/CN=parking-17.com"

    cat /etc/haproxy/ssl/parking.crt /etc/haproxy/ssl/parking.key > /etc/haproxy/ssl/parking.pem
  args:
    creates: /etc/haproxy/ssl/parking.pem

- name: buat file konfigurasi haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: restart haproxy
  service:
    name: haproxy
    state: restarted
    enabled: yes
