- name: install dns
  apt:
    name: [bind9, bind9utils, bind9-doc, dnsutils]
    state: present

- name: konfigurasi zone named.conf.local
  copy:
    dest: /etc/bind/named.conf.local
    content: |
      zone "{{ domain_name }}" {
          type master;
          file "/etc/bind/db.{{ domain_name }}";
      };

- name: buat file zone
  template:
    src: db.parking.j2
    dest: "/etc/bind/db.{{ domain_name }}"

- name: validasi konfigurasi sebelum dinyalakan
  shell: named-checkconf /etc/bind/named.conf.local
  failed_when: false

- name: restart dns
  service:
    name: bind9
    state: restarted
    enabled: yes

- name: tes dns
  shell: |
    sed -i '1i nameserver 127.0.0.1' /etc/resolv.conf
  failed_when: false
